Build
codex-team/moduleDispatcher pull request #2
Opened 2018-01-12 23:01 UTC by PolinaShneider

2018-01-12 23:12 UTC, talyguryn requested changes

2018-01-12 23:12 UTC, talyguryn commented on package.json
> +    "webpack": "^3.10.0"
Хули он тут делает?

2018-01-12 23:12 UTC, talyguryn commented on src/index.js
> +
Пустая строка

2018-01-12 23:12 UTC, talyguryn commented on src/index.js
> +
Две пустые строки

2018-01-12 23:12 UTC, talyguryn commented on webpack.config.js
> +              presets: [ 'es2015' ]
Бейбл при сборке разве не ругается и не просит использовать env вместо es2015?

2018-01-12 23:12 UTC, talyguryn commented on package.json
> +  "description": "CodeX Module Dispatcher",
Напиши нормальный дескрипшн

2018-01-12 23:12 UTC, talyguryn commented on src/index.js
> + *
Зачем тут пустая строка?

2018-01-12 23:12 UTC, talyguryn commented on src/index.js
> +/**
Отступов нет

2018-01-12 23:12 UTC, talyguryn commented on src/index.js
> +
Пустая строка

2018-01-12 23:12 UTC, talyguryn commented on webpack.config.js
> +  library: pkg.exportModuleName,
Имя экспортируешь, но не задаёт нигде

2018-01-13 09:09 UTC, khaydarov requested changes

2018-01-13 09:09 UTC, khaydarov commented on src/index.js
> +/**
это лучше поправить: 
```
/**
 * your description
 */
 your code
```

2018-01-13 09:09 UTC, khaydarov commented on src/index.js
> +/**
и не делай это вручную, а настрой свой редакдор

2018-01-13 09:09 UTC, khaydarov commented on webpack.config.js
> +  }),
будет неплохо если еще сжатую версию добавишь

2018-01-13 09:18 UTC, talyguryn requested changes

2018-01-13 09:18 UTC, talyguryn commented on package.json
> +  "main": "bundle.js",
`lib/bundle.js`

2018-01-13 09:18 UTC, talyguryn commented on webpack.config.js
> +  filename: './lib/bundle.js',
`pkg.main`

2018-01-13 09:18 UTC, talyguryn commented on package.json
> +  "version": "1.0.0",
перед этим добавь
`exportModuleName: "dispatcher",`

2018-01-13 10:18 UTC, talyguryn approved these changes

2018-01-13 10:19 UTC, merged