Renamed project files
codex-team/moduleDispatcher pull request #3
Opened 2018-01-13 11:20 UTC by PolinaShneider

2018-01-13 11:32 UTC, neSpecc requested changes
- Сверху сборки должна быть шапка с описанием библиотеки.
- Readme

2018-01-15 08:01 UTC, neSpecc requested changes

2018-01-15 08:01 UTC, neSpecc commented on bundleComment.js
> +module.exports = (function () {
лишняя функция

2018-01-15 08:01 UTC, neSpecc commented on bundleComment.js
> +    let comment = pkg.description + "\n \n" + "@copyright " + pkg.copyright + "\n" + "@license " + pkg.license + "\n" + "@author " + pkg.author + "\n" + "@version " + pkg.version;
форматирование непонятное и неудобное

2018-01-15 11:40 UTC, neSpecc requested changes

2018-01-15 11:40 UTC, neSpecc commented on package.json
>    "description": "CodeX Module Dispatcher — Class for Modules initialization",
Initialize frontend Modules from the DOM without inline scripts

2018-01-15 11:40 UTC, neSpecc commented on lib/moduleDispatcher.js
> +//# sourceMappingURL=moduleDispatcher.js.map
луче убрать сорсмэпы из продакшен-сборки, их подключать все равно не будут

2018-01-15 11:40 UTC, neSpecc commented on webpack.config.js
> + * @return {String} comment composed from package values
Bundle header with Module description

2018-01-15 13:44 UTC, neSpecc approved these changes

2018-01-15 19:59 UTC, khaydarov approved these changes

2018-01-15 20:07 UTC, talyguryn reviewed
Теперь можно поднять версию до 1.0.0, смерджить и опубликовать в нпм

2018-01-15 20:29 UTC, merged