Use hidden textarea to pass settings
codex-team/moduleDispatcher pull request #9
Opened 2019-02-01 13:43 UTC by PolinaShneider

Closes #8

2019-02-01 13:46 UTC, gohabereg approved these changes

2019-02-05 12:47 UTC, khaydarov requested changes

2019-02-05 12:47 UTC, khaydarov commented on README.md
> +Don't forget to add an attribute `hidden` to the `<textarea>` tag
добавь сюда еще про уязвимость xss. Напиши что обязательно нужно эскейпить данные

2019-02-05 15:05 UTC, talyguryn approved these changes
выглядит норм

2019-02-05 16:54 UTC, talyguryn requested changes

2019-02-05 16:54 UTC, talyguryn commented on example.html
> +    </div>
```suggestion
    Open console to see Dispatcher's work result
    </div>
```

ну или что-то такое

2019-02-05 17:03 UTC, talyguryn approved these changes

2019-02-06 05:38 UTC, khaydarov approved these changes

2019-02-06 18:57 UTC, merged